### ISSUE TITLE
`fpZ` not working

### ISSUE THREAD

**Issue by hazzyeer** [imgix/gatsby#115]
Hello,

GraphQL does not allow hyphenated names. The property `fpZ` just get past to the generated URL and Imgix does not seem to know what to do with it (`fpZ=1` instead of `fp-z=1`).

I'm using the version `1.6.0`.

Thanks.

**Comment by frederickfogerty** [comment]
Hey there @hazzyeer - this shouldn't be happening. Can you please let me know what your GraphQL query is, and how you're using the plugin? Then I'll be able to take a look at this. Thanks!

**Comment by hazzyeer** [comment]
Version of the dependency that i'm using "@imgix/gatsby": "^1.6.0".
Here is my configuration of the plugin:
```
{
    resolve: `@imgix/gatsby`,
    options: {
      domain: '<domain>',
      secureURLToken: '<token>',
      sourceType: ImgixSourceType.WebFolder,
      defaultImgixParams: { auto: 'format,compress' },
      fields: [
        {
          nodeType: 'Image',
          // This is used to pull the raw image URL from the node you want to
          // transform. It is passed the node to transform as an argument, and
          // expects a URL to be returned.
          getURL: (node) => {
            const urlBlocks: ReadonlyArray<string> = node.url.split('/')
            return urlBlocks[urlBlocks.length - 1]
          },
          // This is the name of imgix field that will be added to the type.
          fieldName: 'imgixImage',
        }
      ]
    },
  }
```
And here is the graphql query:
```
image {
        ...
        imgixImage {
          gatsbyImageData(
            layout: FIXED
            width: 70
            imgixParams: {auto: "format,compress", ar: "0.74", fit:"crop", fpZ: 4, crop: "focalpoint"}
          )
        }
      }
```

**Comment by frederickfogerty** [comment]
Hi there @hazzyeer, thanks for providing that information! I investigated this today and implemented a fix so I've closed out this issue. If you are still having issues, please comment here and I'll take another look. Thanks again!
