### ISSUE TITLE
Use multiple sources within the same project

### ISSUE THREAD

**Issue by asterikx** [imgix/gatsby#130]
**Before you submit:**

- [x] Please search through the existing issues (both open AND closed) to see if your question has already been discussed. Github issue search can be used for this: https://github.com/imgix/gatsby/issues?utf8=%E2%9C%93&q=is%3Aissue

**Question**
Is it possible to use images from multiple imgix sources within the same Gatsby project? E.g. images from a CMS (through a `Web Proxy Source`) and images from a S3 bucket (through a `Amazon S3 Source`)?

Thanks for any hints.

**Comment by sherwinski** [comment]
Hey @asterikx and thanks for opening this issue.
Let me go back to the team with this and see if there's a documented example we can share.

**Comment by frederickfogerty** [comment]
Hey there @asterikx 👋 thanks for opening this issue.

At this stage multiple sources is only supported by the [URL transform function](https://github.com/imgix/gatsby#url-transform-function), and not within the GraphQL API. With the transform function you can pass any imgix URL from any source, for example:

```js
import { ImgixGatsbyImage } from '@imgix/gatsby';

export const MyPageComponent = () => (
  <div>
    <ImgixGatsbyImage src="https://first-source.imgix.net/image.jpg" />
    <ImgixGatsbyImage src="https://second-source.imgix.net/image.jpg" />
  </div>
);
```

Of course this could also be combined with the GraphQL API to support multiple sources too. So in your case, the GraphQL API could support the Web Proxy source, and the URL transform function could support the S3 bucket images. 

I'm interested to hear what your thoughts are on this. We will also try and document this feature in our README.
