### ISSUE TITLE
getGatsbyImageData() returns larger images than needed in scrSet

### ISSUE THREAD

**Issue by OleksandrRakovets** [imgix/gatsby#143]
I am trying to constrain image width depending on screen sizes. On the largest screen the image is limited to 1040px width, on tablet it takes about 80% width and full width on mobile.

Even though I set breakpoints and maxWidth, the srcSet values from `getGatsbyImageData()` contains `w` units which results in loading 1280px wide image. Taking into account retina display, I expect the largest width to maybe appear as 2080px, but 1280px is useless in any of my cases.

<img width="673" alt="Screenshot 2021-11-02 at 17 28 37" src="https://user-images.githubusercontent.com/5619390/139878762-e39d0827-36db-4cfd-901f-011ee9edfc3f.png">

I've extracted my attempted code into [a CodeSandbox](https://codesandbox.io/s/gatsby-image-data-issue-1fq8z?file=/src/index.js).

Please advise, can I set width in pixels in srcSet for my breakpoints?

**Comment by frederickfogerty** [comment]
Hi @OleksandrRakovets 👋  thanks for opening this issue. Unfortunately, the srcset widths returned here are not generated by this library - this library only consumes the recommended srcset widths from the Gatsby built-in helpers. If you would like to discuss the implementation of this, I recommend you discuss it over on the Gatsby repo.
