### ISSUE TITLE
Js-core being exported in production as 57.7kb

### ISSUE THREAD

**Issue by ChrisBudetti** [imgix/gatsby#181]
v2.0

All types are being exported when using the frontend hook. Bundlephobia is unable to check size https://bundlephobia.com/package/@imgix/gatsby

Steps to reproduce

1. import { getGatsbyImageData } from "@imgix/gatsby"
2. View bundle size

<img width="479" alt="image" src="https://user-images.githubusercontent.com/1588849/160324198-64fa407b-b720-4e32-8a4a-86fb09d990c5.png">

**Comment by sherwinski** [comment]
Hey @ChrisBudetti and thanks for opening this issue. I've noted this issue in our team's backlog so that  we can set some time aside to look into it soon. I'll be sure to follow up with any updates or questions here.

**Comment by luqven** [comment]
Hey @ChrisBudetti, 

The latest release, [v2.0.4](https://github.com/imgix/gatsby/releases/tag/v2.0.4), appears to show the dependencies on [bundlephobia](https://bundlephobia.com/package/@imgix/gatsby) correctly.

You'll note the bundle size change as a result of re-factoring out the `fp-ts` package and introducing the `joi` dependency.

For now, it looks like it's safe to close this issue. But if I've missed anything please don't hesitate to comment and I can come back and re-open this.

Thanks!
