### ISSUE TITLE
Is it possible to sign URLs when using the `getGatsbyImageData` hook?

### ISSUE THREAD

**Issue by campezzi** [imgix/gatsby#216]
I noticed the image URLs returned by the `getGatsbyImageData` hook are unsigned, causing issues when trying to render images from an Imgix source that has Secure URLs enabled. For example, attempting to pass the following in the `image` prop to `GatsbyImage` fails with a 403 error:

```
getGatsbyImageData({
  aspectRatio: 16/9,
  layout: "fullWidth",
  src: someImgixImageURL,
})
```

If secure URLs are disabled in the Imgix source, images are rendered without a hiccup. Additionally, the `secureURLToken` is configured correctly - images rendered with different integration methods throughout the site are being signed properly.

Is this a limitation of `getGatsbyImageData` (because it would otherwise expose the secure URL token to the browser) or is there something I'm missing?

Thanks in advance!

**Comment by luqven** [comment]
Hey @campezzi, I wanted to take a second to follow up on this.

Did angelo's suggestion work for you?

**Comment by luqven** [comment]
I'm going to go ahead and close this issue, but should anything else come up please do comment and I'll be sure to open it again.
