### ISSUE TITLE
deprecated gatsby-image@3.11.0 dependency

### ISSUE THREAD

**Issue by rubas** [imgix/gatsby#223]
```

npm WARN deprecated gatsby-image@3.11.0: gatsby-image is now gatsby-plugin-image: https://npm.im/gatsby-plugin-image. This package will no longer receive updates.

```
https://github.com/imgix/gatsby/blob/main/package.json#L79

**Comment by sherwinski** [comment]
Hey @rubas, thanks for the heads up here. We'll set some time aside to investigate this and the potential lift it would take to migrate dependencies.
