### ISSUE TITLE
`disableIxlibParam` doesn't work

### ISSUE THREAD

**Issue by arsinclair** [imgix/gatsby#228]
1. The **disableIxlibParam** setting doesn't work. When it is not set (or set to false), the URLs generated look like this: `https://domain.net/image.jpg?ixlib=gatsbySourceUrl-2.0.2`. When it is set to _true_, the URLs look like this: `https://domain.net/image.jpg?ixlib=js-3.5.1`.

I expect that `disableIxlibParam` should disable any variation of _ixlib_ param.

2. Another question is why something that's claimed to be a diagnostic mechanism is enabled by default? Can we switch it off by default? Imagine that a security vulnerability is found in a specific version of a plugin. Exposing the version of the library in the URLs of every image can expedite identification of many vulnerable sites that use this specific version.

4. The documentation (README.md) has some discrepancies: sometimes it says that do disable the _ixlib_ param, one needs to set `includeLibraryParam` to `false`, other times it says that in order to disable it, `disableIxlibParam` should be set to `true`. None of this settings (and their combination) allows to disable the version of the library entirely. 

**Information:**

- imgix/gatsby version: 2.0.3
- browser version: Chrome 104

**Comment by atlawrie** [comment]
Hello and thank you for bringing this to our attention. You’re right that `disableIxlibParam` isn’t working as intended; we’ve identified the cause of the issue internally and should be rolling out a fix sometime this upcoming week.

In the past, the library parameter has been useful for users who write in to our support channel. Having information on-hand like the library where the request originated from has allowed us to provide smoother support more quickly. The good news is that with the subsequent fix we are making, you should be able to globally disable the library parameter through the gatsby-config file [[1](https://github.com/imgix/gatsby#gatsbyplugin-configuration) ][[2](https://github.com/imgix/gatsby#configuration) ].

In terms of the differences between `disableIxlibParam` and `includeLibraryParam`, this is mostly a difference of usage and scope. disableIxlibParam is used as a setting in `gatsby-config.js`, letting the user for instance disable the ixlib paramters by default, while `includeLibraryParam` is used on a function by function basis, letting the user override their global setting depending on their need. You’re absolutely right that our documentation is unclear on this point, and we’re planning on updating that alongside our fix.

**Comment by arsinclair** [comment]
It's good to know this is a bug. Do you have a time estimate when the fix will be ready?

**Comment by atlawrie** [comment]
Hi @arsinclair, we’ve located and fixed the bug, but we've come across some high priority issues that are preventing us from rolling out a new release. We don’t currently have an ETA for when we’ll be deploying the update, but we’ll make sure keep you posted.

**Comment by atlawrie** [comment]
Hi @arsinclair, we've deployed our fix for this issue in 2.0.4.
