### ISSUE TITLE
Gatsby V5 support - graphql dependency

### ISSUE THREAD

**Issue by finematterdave** [imgix/gatsby#246]
**Before you submit:**

- [x] Please read the [contributing guidelines](CONTRIBUTING.md)
- [x] Please search through the existing issues (both open AND closed) to see if your issue has been discussed before. Github issue search can be used for this: https://github.com/imgix/vue/issues?utf8=%E2%9C%93&q=is%3Aissue
- [x] Please ensure the problem has been isolated and reduced. This link explains more: http://css-tricks.com/6263-reduced-test-cases/

**Describe the bug**
After upgrading to Gatsby 5, which has a dependency on graphql 16, the plugin fails to load due to a dependency on version 15.

For reference, error when using v16 of graphql is `TypeError: Class constructor GraphQLNonNull cannot be invoked without 'new'`.

I'll try and work on this as a PR, but just to raise it incase there's already a reason it's not upto date.

**To Reproduce**
Install Gatsby v5, with the @imgix/gatsby plugin configured, fails during build with error above

**Expected behaviour**
Build passes as expected

**Comment by atlawrie** [comment]
Hey thanks for looking into this. We’re working on V5 support currently but we have some other things on our plate, but we’ll circle back soon when we have the bandwidth.

**Comment by finematterdave** [comment]
https://github.com/imgix/gatsby/pull/249 a basic working PR which we're using as a fork for now until your team have some capacity to look into it.

**Comment by luqven** [comment]
Merged in #259 

@finematterdave, thanks again for your work on this!
