### ISSUE TITLE
Gatsby source for images from image manager

### ISSUE THREAD

**Issue by frederickfogerty** [imgix/gatsby#6]
_This is a potential feature for this library. If you want to see us build this, please indicate your support by reacting to this with a 👍_

### User Story

I have an image stored in image manager that I want to render.

### Description

This would provide a Gatsby source that would allow developers to display any images available in imgix's new image manager product.

For example, in a Gatsby page query:

```gql
{
	allImgixImages {
		name
		url(imgixParams: {auto: ["compress"]}) { url }
		owner
		modifiedAt
	}
}
```

**Comment by sherwinski** [comment]
Closing as there hasn't been much movement here but I have noted this feature in our backlog.
