### ISSUE TITLE
Unable to use focal point

### ISSUE THREAD

**Issue by richardfrankza** [imgix/gatsby#61]
Hi there

GraphQL does not allow hyphenated names. There are properties fpY, fpX but these just get passed to the generated URL and Imgix does not seem to know what to do with them. What am I doing wrong?

Why are fpX and fpY integers, shouldn't they be floats?

Thanks,
Richard

**Comment by frederickfogerty** [comment]
Hi there @richardfrankza 👋 thanks for reporting this issue. This must have slipped through the cracks - I'll take a look at this soon and get back to you here.
